[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ncoreparser"
version = "1.9.2"
description = "Package to download from ncore.pro"
authors = [
  { name="Aron Radics", email="aron.radics.jozsef@gmail.com" }
]
license = "MIT"
readme = "Readme.md"
dependencies = [
  "httpx>=0.26.0",
]

[project.optional-dependencies]
dev = ["pytest", "flake8"]
